# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: OESS
email: oess-users@globalnoc.iu.edu
description: >- # this means to ignore newlines until "baseurl:"
  The Network Development and Deployment Initiative (NDDI), a
  partnership between Internet2, Indiana University and others was
  formed to create a new network platform and complementary software,
  which together will support global scientific research in a
  revolutionary new way. The Open Exchange Software Suite (OESS) is the
  first software product to emerge from this partnership.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: iuglobalnoc
github_username:  GlobalNOC

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

header_pages:
#  - api.md
#  - frontend.md
  - the-basics.md
  - user-documentation.md
  - operations-manual.md
  - administration.md

collections:
  api_endpoints:
    output: true
    permalink: /api/:name
